# -*- coding: utf-8 -*-
from schemaorgschemas.Thing import potentialActionProp, descriptionProp, sameAsProp, imageProp, urlProp, mainEntityOfPageProp, additionalTypeProp, alternateNameProp, nameProp

from schemaorgschemas.djangoschema import SchemaObject, SchemaProperty, SchemaEnumProperty, SCHEMA_ORG
from django.conf import settings


class ServiceSchema(SchemaObject):

    """Schema Mixin for Service
    Usage: place after django model in class definition, schema will return the schema.org url for the object
    A service provided by an organization, e.g. delivery service, print services, etc.
    """

    def __init__(self):
        self.schema = 'Service'


class aggregateRatingProp(SchemaProperty):

    """
    SchemaField for aggregateRating
    Usage: Include in SchemaObject SchemaFields as your_django_field = aggregateRatingProp()  
    schema.org description:The overall rating, based on a collection of reviews or ratings, of the item.

    prop_schema returns just the property without url#
    format_as is used by app templatetags based upon schema.org datatype
    used to reference AggregateRating"""

    _prop_schema = 'aggregateRating'
    _expected_schema = 'AggregateRating'
    _enum = False
    _format_as = "ForeignKey"


class serviceTypeProp(SchemaProperty):

    """
    SchemaField for serviceType
    Usage: Include in SchemaObject SchemaFields as your_django_field = serviceTypeProp()  
    schema.org description:The type of service being offered, e.g. veterans&#39; benefits, emergency relief, etc.

    prop_schema returns just the property without url#
    format_as is used by app templatetags based upon schema.org datatype
    """

    _prop_schema = 'serviceType'
    _expected_schema = None
    _enum = False
    _format_as = "TextField"


class serviceOutputProp(SchemaProperty):

    """
    SchemaField for serviceOutput
    Usage: Include in SchemaObject SchemaFields as your_django_field = serviceOutputProp()  
    schema.org description:The tangible thing generated by the service, e.g. a passport, permit, etc. Supersedes produces.

    prop_schema returns just the property without url#
    format_as is used by app templatetags based upon schema.org datatype
    used to reference Thing"""

    _prop_schema = 'serviceOutput'
    _expected_schema = 'Thing'
    _enum = False
    _format_as = "TextField"


class availableChannelProp(SchemaProperty):

    """
    SchemaField for availableChannel
    Usage: Include in SchemaObject SchemaFields as your_django_field = availableChannelProp()  
    schema.org description:A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).

    prop_schema returns just the property without url#
    format_as is used by app templatetags based upon schema.org datatype
    used to reference ServiceChannel"""

    _prop_schema = 'availableChannel'
    _expected_schema = 'ServiceChannel'
    _enum = False
    _format_as = "ForeignKey"


class serviceAreaProp(SchemaProperty):

    """
    SchemaField for serviceArea
    Usage: Include in SchemaObject SchemaFields as your_django_field = serviceAreaProp()  
    schema.org description:The geographic area where the service is provided. Supersedes area.

    prop_schema returns just the property without url#
    format_as is used by app templatetags based upon schema.org datatype
    used to reference AdministrativeArea"""

    _prop_schema = 'serviceArea'
    _expected_schema = 'AdministrativeArea'
    _enum = False
    _format_as = "ForeignKey"


class reviewProp(SchemaProperty):

    """
    SchemaField for review
    Usage: Include in SchemaObject SchemaFields as your_django_field = reviewProp()  
    schema.org description:A review of the item. Supersedes reviews.

    prop_schema returns just the property without url#
    format_as is used by app templatetags based upon schema.org datatype
    used to reference Review"""

    _prop_schema = 'review'
    _expected_schema = 'Review'
    _enum = False
    _format_as = "ForeignKey"


class providerProp(SchemaProperty):

    """
    SchemaField for provider
    Usage: Include in SchemaObject SchemaFields as your_django_field = providerProp()  
    schema.org description:The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller. Supersedes carrier.

    prop_schema returns just the property without url#
    format_as is used by app templatetags based upon schema.org datatype
    used to reference Organization"""

    _prop_schema = 'provider'
    _expected_schema = 'Organization'
    _enum = False
    _format_as = "ForeignKey"


# schema.org version 2.0
